# Generated by Django 4.2.2 on 2023-09-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_book_is_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_return',
            field=models.CharField(blank=True, default='no', max_length=3, null=True),
        ),
    ]
